#!/usr/bin/env bash
# Bash script that displays:
# 	- content of current directory
#	- in a list format
# 	- only the part of the name after the first dash is displayed

files="$(ls)"
for file in $files;
do
	echo "$file" | cut -d "-" -f2
done