#!/usr/bin/env bash
# Running nginx as nginx and fixing port from 80 to 8080
#!/bin/bash

# Step 1: Update Nginx configuration
sed -i 's/^user .*/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/\blisten\s*80\b/listen 8080/g' /etc/nginx/nginx.conf
